//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexicon.Legacy2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LexiconRaw
    {
        public int Id { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Entry { get; set; }
        public string Meaning { get; set; }
        public string SecondaryMeanings { get; set; }
        public string Pos { get; set; }
        public Nullable<int> PosCode { get; set; }
        public string PosSubtype { get; set; }
        public string Gender { get; set; }
        public string NounIncorporatedForm { get; set; }
        public string AlternateForms { get; set; }
        public string Dialect { get; set; }
        public string Register { get; set; }
        public string Domain { get; set; }
        public string Synonyms { get; set; }
        public string Etymology { get; set; }
        public string IPA { get; set; }
        public string GrammaticalNotes { get; set; }
        public string AdditionalNotes { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
    }
}
