//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexicon.Legacy2019.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lexicon2019_TransitionalEntities : DbContext
    {
        public Lexicon2019_TransitionalEntities()
            : base("name=Lexicon2019_TransitionalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dialect> Dialects { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<Gloss> Glosses { get; set; }
        public DbSet<LanguageFamily> LanguageFamilies { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<LexiconRaw> LexiconRaws { get; set; }
        public DbSet<POS> POS { get; set; }
    }
}
