//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexicon.Legacy2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS
    {
        public int Id { get; set; }
        public int SortOrder { get; set; }
        public string Name { get; set; }
        public string Gloss { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
    }
}
